//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public FileLog()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public int Manager_Id { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
